### ISSUE TITLE
Clear screen support (^L/Form-feed and "tput clear")

### ISSUE THREAD

**Issue by nanobot248** [sedwards2009/extraterm#76] opened 2018-02-23 18:46 UTC
In most terminals. pressing `CTRL+L` (inserts form-feed control character) or executing `clear` or `tput clear` in the shell clears the terminal.
There doesn't seem to be any such functionality in extraterm, which means the prompt will stay at the bottom of the terminal most of the time.
Like in e.g. gnome-shell or konsole, this should not clear the scrollback buffer, just clear the current screen and put the cursor in the top left position.

**Comment by sedwards2009** [comment] 2018-02-23 19:30
Thanks for the report. It is a duplicate of #15 though.

**Closed by sedwards2009** 2018-02-23 19:30 UTC
