### ISSUE TITLE
crash on hardened kernel

### ISSUE THREAD

**Issue by deathtrip** [sedwards2009/extraterm#263] opened 2020-05-06 23:30 UTC
When trying to start extraterm on Arch Linux's [hardened kernel](https://www.archlinux.org/packages/extra/x86_64/linux-hardened/) i get this:
`[83343:0507/000439.129126:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly.Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/extraterm/chrome-sandbox is owned by root and has mode 4755.
/usr/bin/extraterm: line 2: 83343 Trace/breakpoint trap   (core dumped) /opt/extraterm/extraterm`

On vanilla kernel everything worked fine when i tested it awhile ago.
It's strange that extraterm's sandbox crashes while chromium works just fine on hardened kernel.

**Comment by deathtrip** [comment] 2020-05-09 23:49
Well, i managed to get it started by `# chmod 4755 chrome-sandbox`.
Must be a packaging error then. I still wonder why it only happens on the hardened kernel though.
At first I assumed it was the kernels fault, now i have no clue...

**Comment by sedwards2009** [comment] 2020-05-10 07:53
This is duplicate of #228 

As mentioned in 228, the .deb files in the nightly builds should now correctly set the permissions on `chrome-sandbox`. You can find these builds at: https://storage.googleapis.com/extraterm_builds/index.html

**Closed by sedwards2009** 2020-05-10 07:53 UTC
