### ISSUE TITLE
Extraterm crashes on start if FontBase is running

### ISSUE THREAD

**Issue by gaia** [sedwards2009/extraterm#290] opened 2020-10-10 18:55 UTC
install https://fontba.se/ current (2.13.2)
install extraterm current (0.53.1)

start fontbase
try to start extraterm. it crashes and leaves dangling processes. i tried to uninstall/reinstall/downgrade (it has been working wonderfully for over a year).

now exit fontbase.
extraterm starts fine.

it doesn't seem like a Fontbase problem, because fontbase starts fine with extraterm running.

there is some conflict with font handling. try to replicate you will see the message.

**Comment by sedwards2009** [comment] 2020-10-11 20:35
Which operating system are you using?

**Comment by gaia** [comment] 2020-10-11 23:30
sorry, should have included that: Win 10 19041.508

**Comment by gaia** [comment] 2020-10-12 22:04
![image](https://user-images.githubusercontent.com/87547/95794240-4828d880-0c9c-11eb-95e2-5cdd054c71f5.png)

**Comment by sedwards2009** [comment] 2020-10-13 08:10
If you run that `list-fonts-json.exe` directly from the normal windows cmd or powershell, do you get any output or anything different?

I think I'm just going to have to cook up a version is full of debug output and ask you to run it and report what happened.

**Comment by gaia** [comment] 2020-10-13 15:42
I did run it directly. This is how I found that fontbase had copied about 4700 fonts to its own folder, and added the fontbase path to the registry.

it took a while scrolling thru all the fonts, and when it stopped I was able to see a path for fonts which I did not know existed (the duplicate copies)

**Comment by sedwards2009** [comment] 2020-10-14 18:10
The duplicate copies shouldn't matter too much as `list-fonts-json.exe` shouldn't care too much. (Actually, it ignores duplicates.)

I've changed `list-fonts-json.exe` a bit now such that if it does crash then we have a better chance of getting useful info out of it.

Since you can't reproduce the bug right now, I'm just going to close this issue. Re-open or create a new issue if it happens again.

Thanks for the investigating.

**Closed by sedwards2009** 2020-10-14 18:10 UTC
