### ISSUE TITLE
Option to allow closing terminal without confirmation

### ISSUE THREAD

**Issue by cebaa** [sedwards2009/extraterm#274] opened 2020-07-21 20:38 UTC
Option to allow closing terminal without confirmation:

```
[Process exited. Press Enter to close this terminal.] 
```

**Comment by sedwards2009** [comment] 2020-07-24 21:03
The problem is that this behaviour was added for a reason. If the session fails to start for whatever reason then the info needed to solve the problem disappears before you can see it. So we need something handles that case and somehow doesn't hold up exiting a session normally.

Some kind of timer based approach may work. Show message on exit if the session is less than 5 seconds old, for example.

**Comment by cebaa** [comment] 2020-07-27 16:05
>  If the session fails to start for whatever reason then the info needed to solve the problem disappears before you can see it.

I get that, that might be another option. I've ConEmu with this disable and so far never had that issue - worst thing is, if it doesn't start repeatedly, I can uncheck and start again.

**Comment by sedwards2009** [comment] 2020-11-17 20:32
Fixed in 0.55.1. The terminal only stays open on exit if the shell returned a non-zero exit code.

**Closed by sedwards2009** 2020-11-17 20:32 UTC
Labels: enhancement, prio:medium
