### ISSUE TITLE
Error opening second instance

### ISSUE THREAD

**Issue by Chagui-** [sedwards2009/extraterm#183] opened 2019-04-10 14:10 UTC
In WIndows 10, after installing extraterm, i can open it once, but when i try to open it again (to run 2 instances at the same time) i get the following error:
![image](https://user-images.githubusercontent.com/3289167/55885883-ba38d280-5b78-11e9-977b-e5af904d391a.png)

**Comment by sedwards2009** [comment] 2019-04-11 17:00
Duplicate of issue #115

**Closed by sedwards2009** 2019-04-11 17:00 UTC
