### ISSUE TITLE
The clear command doesn't

### ISSUE THREAD

**Issue by scirocco6** [sedwards2009/extraterm#80] opened 2018-03-18 22:56 UTC
macOS 10.13.3
extraterm v1.6.8
zsh 5.3 (x86_64-apple-darwin17.0)

Typing the clear command should clear the screen.  Instead it just shows a normal command succeeded blue box
![screen shot 2018-03-18 at 6 54 46 pm](https://user-images.githubusercontent.com/3019374/37572192-e20303e8-2add-11e8-9b74-d8f74cdfdfcc.png)

**Comment by sedwards2009** [comment] 2018-03-19 17:39
Dupe of #15.

**Comment by sedwards2009** [comment] 2018-03-19 17:41
thanks for reporting this even though it is a duplicate.

**Closed by sedwards2009** 2018-03-19 17:41 UTC
