### ISSUE TITLE
Multiple cursor support

### ISSUE THREAD

**Issue by gottfired** [sedwards2009/extraterm#71] opened 2018-01-22 08:06 UTC
Multiple cursor support with cmd+d/ctrl+d similar to Sublime or VSCode would be great. I know you can do a column select, but this would be more flexible.

**Comment by sedwards2009** [comment] 2018-01-22 08:29
Right now when you're in cursor mode you can use control+click to place a 2nd (or 3rd etc) cursor. Also Ctrl+Shift+| will also turn a multiline selection into multiple cursors.

The exact keys may be different depending on which OS you are using. (I just tested on cygwin/Windows).

I'll keep this issue open though because I want to go back and make the multiple cursor functionality and shortcuts work much closer (=exactly) like VSCode. Extraterm doesn't have a command quite like Ctrl+D at the moment.

**Comment by gottfired** [comment] 2018-01-22 12:21
Ah thanks. I didn't know that.

**Comment by sedwards2009** [comment] 2018-08-18 11:39
#109 should have been closed as a duplicate of this issue. Both issues will be closed after the next release.

**Closed** 2018-08-23 21:58 UTC
Labels: enhancement, prio:medium
