### ISSUE TITLE
New Tab Directory

### ISSUE THREAD

**Issue by ceyhunkerti** [sedwards2009/extraterm#223] opened 2019-10-13 14:06 UTC
This is just a suggestion;
Lets say my current dir. is `/path/to/dir` when i open new tab the new tab's directory
can be the same `/path/to/dir` instead of `home`

**Comment by sedwards2009** [comment] 2019-10-21 08:50
Duplicate of #38 

thanks for mentioning this though.

**Closed by sedwards2009** 2019-10-21 08:50 UTC
