### ISSUE TITLE
Feature Request: Transparency

### ISSUE THREAD

**Issue by jwhipp** [sedwards2009/extraterm#181] opened 2019-04-09 17:27 UTC
This is a feature request to handle background transparency, preferably with configurable levels of opacity.   In Hyper on Windows, this is achieved with a plugin, some other terminals (ConEMU) it's just native.    A similar feature in Extraterm would be amazing.

**Comment by sedwards2009** [comment] 2019-04-11 16:56
Duplicate of issue #66

**Closed by sedwards2009** 2019-04-11 16:56 UTC

**Comment by jwhipp** [comment] 2019-04-11 16:59
Apologies for the duplicate, for some reason, I didn't get added as a watcher to #66 and totally forgot it about it.
