### ISSUE TITLE
Open url links in browser

### ISSUE THREAD

**Issue by ceyhunkerti** [sedwards2009/extraterm#222] opened 2019-10-13 13:05 UTC
Is there a way to open url links in default browser ?
Like ctrl + click

![image](https://user-images.githubusercontent.com/6328046/66716122-253abe80-edd3-11e9-862e-33f3d4498076.png)

**Comment by sedwards2009** [comment] 2019-10-13 18:57
This is very close to #92 except that you probably want automatic link detection.

**Comment by sedwards2009** [comment] 2019-10-13 18:59
Duplicate of  #173

**Closed by sedwards2009** 2019-10-13 18:59 UTC
Labels: enhancement, prio:low
