### ISSUE TITLE
*** Initial directory 'null' couldn't be found. *** on Linux

### ISSUE THREAD

**Issue by caedmon-kitty** [sedwards2009/extraterm#327] opened 2021-02-05 22:30 UTC
Appears to be the same as #310.
I am using 0.57.1
Occurs with both zsh and fish.
Initial directory is correctly set in extraterm.json
The window does open in the correct initial directory.

**Comment by sedwards2009** [comment] 2021-02-13 20:29
Can you attach or paste the contents of `~/.config/extraterm/extraterm.json` here?

**Comment by caedmon-kitty** [comment] 2021-02-16 23:13
Attached.

**Comment by caedmon-kitty** [comment] 2021-02-16 23:14
Attached

[extraterm.json.gz](https://github.com/sedwards2009/extraterm/files/5992189/extraterm.json.gz)

**Comment by sedwards2009** [comment] 2021-02-17 20:59
Thanks. I can reproduce the problem here.

**Comment by sedwards2009** [comment] 2021-02-17 21:20
Dupe of #318

**Comment by sedwards2009** [comment] 2021-02-19 21:09
Fixed in v0.58.0.

**Closed by sedwards2009** 2021-02-19 21:09 UTC
Labels: bug, fixed
