### ISSUE TITLE
Can't make @ symbol in Windows 10

### ISSUE THREAD

**Issue by maetthew** [sedwards2009/extraterm#136] opened 2018-12-06 22:43 UTC
Hi,

I just discovered Extraterm yesterday and decided to give it a shot. I'm having a weird issue though, I can't make the @ symbol in Extraterm for some reason. I'm using a swedish keyboard layout and for some reason I can't get it to work. The keyboard shortcut on a swedish keyboard layout is "altgr+2".

I searched for similar issues but couldn't find anything. This is a peculiar problem that only shows in Extraterm and I'm at loss what to try.

**Comment by sedwards2009** [comment] 2018-12-07 11:37
This sounds the same as https://github.com/sedwards2009/extraterm/issues/97

**Comment by maetthew** [comment] 2018-12-07 12:56
Yeah it's similar but I don't think it's the same. I have no problems making the @ symbol in any other applications including other terminal emulators(WSL Terminal, Hyper, MobaXTerm). I also dont get the "^@" output when trying to make an "@" in CMD as the OP mentioned in the issue you referenced.

You still think these are related?

**Comment by maetthew** [comment] 2018-12-08 00:17
I now realise I forgot to mention that other altgr combinations work fine.

**Comment by maetthew** [comment] 2018-12-08 02:10
After some more using I realised I couldn't make a backspace(altgr+plus sign) in nano and it seem to have sent ^\ (search and replace function in nano).

If I in bash hold down AltGr and just press the 12 buttons on the number row of the keyboard sequentially starting with 1 the output is: `£$€{`
"£" = 3, "$" = 4, "€" = 5, "{" =0 <- keys on keyboard

**Comment by sedwards2009** [comment] 2018-12-08 13:42
I just tried this out on Windows 10 using English and Swedish keymap. VSCode gives @ for right-Alt 2, which is expected. Extraterm gives nothing, which is good because it means that I can reproduce the problem and somewhere in VSCode there is a solution to be found. ;-)

**Comment by maetthew** [comment] 2018-12-08 13:57
Nice :) Keeping my fingers crossed!

**Comment by sedwards2009** [comment] 2018-12-08 15:37
Interestingly Chrome/Blink version 67 contains a fix for AltGr keys on Windows:  https://www.chromestatus.com/features/5059438092222464

This fix will be in Electron v4 which is currently in beta testing. Extraterm is on the (fairly) old 2.x versions of Electron at the moment. If the keyboard work-around for Electron 2.x is too nasty then I might wait for Electron v4 to be properly released first.

**Comment by sedwards2009** [comment] 2018-12-09 14:43
I have a fix for this. I'll probably do a small big fix point release sometime this coming week.

**Closed** 2018-12-09 22:06 UTC
Labels: bug, prio:high, windows

**Comment by sedwards2009** [comment] 2018-12-10 18:43
@maetthew I just released 0.38.1 with this fix in it.

**Comment by maetthew** [comment] 2018-12-10 21:07
@sedwards2009 Yup, confirming both @ and \ works :) 

Output of earlier mentioned method: `@£$€{[]}\ `

Nice job! Can't wait to see where you're gonna take this development.
