### ISSUE TITLE
residual image on screen

### ISSUE THREAD

**Issue by friskit-china** [sedwards2009/extraterm#146] opened 2018-12-25 11:57 UTC
After entered the bash (Windows Subsystem of Linux), my screen will have some residual characters on the screen, It is blinking when I use my keyboard. just like this:

![image](https://user-images.githubusercontent.com/2494883/50421922-5287a180-087f-11e9-8713-85fa6a4384fe.png)

**Comment by sedwards2009** [comment] 2018-12-25 17:42
This appears to be the same problem as #137.

**Comment by sedwards2009** [comment] 2018-12-25 17:47
@friskit-china  What kind of CPU and GPU are you running on?

**Comment by friskit-china** [comment] 2018-12-26 02:30
HP EliteDesk 800 G2 TWR:
i7-6700 with Intel HD Graphics 530 (without dedicated graphics card), Windows 10 Enterprise (1703). 
I have two displays.

**Comment by friskit-china** [comment] 2018-12-26 02:33
> This appears to be the same problem as #137.

I think the user in #137 and me are using the same desktop computer model: HP EliteDesk 800 G2 TWR

**Comment by sedwards2009** [comment] 2018-12-26 08:53
@friskit-china I see the same problem on my work Windows laptop. I has an i7 intel with the integrated gfx too.

**Comment by sedwards2009** [comment] 2018-12-26 08:53
dupe of #137

**Closed by sedwards2009** 2018-12-26 08:53 UTC
