### ISSUE TITLE
Tilix-like panes/tabs

### ISSUE THREAD

**Issue by almson** [sedwards2009/extraterm#312] opened 2020-11-30 07:06 UTC
Extraterm looks very cool, but I just can't switch to it from Tilix because the tab/pane management is much worse.

To sum up, what works really well in tilix is: 
* Tabs are not inside panes. Instead, panes are inside tabs (called "sessions"). This makes more sense. Each tab is like a desktop workspace with horizontal and vertical splits arranged for a particular task.
* Alt+number to switch between panes
* Ctrl+Alt+number to switch between tabs

**Comment by ashb** [comment] 2020-11-30 12:25
Dupe/can be folded in to https://github.com/sedwards2009/extraterm/issues/242 ?

**Comment by sedwards2009** [comment] 2020-11-30 23:11
Thanks @ashb . This is duplicate of issue #242 .

Extraterm supports multiple windows. Arranging splits/panes inside windows is fairly close approximation to what is being requested here.

The tabs, splits, and panes now work in the same way as other software like text editors. Changing it to how Tilix works is a big change to how the application works.

**Closed** 2020-11-30 23:11 UTC
Labels: duplicate
