### ISSUE TITLE
Transparent & Blur causes highlighted text to become unreadable

### ISSUE THREAD

**Issue by fhumayun** [sedwards2009/extraterm#283] opened 2020-09-25 06:51 UTC
Hi guys - 
Steps to reproduce
1-  Settings -> Select any default extraterm theme
2-  Settings -> Interface -> Window Background:  Transparent and Blur activated
Notice you cannot read highlighted text in the terminal (e.g. man page )
3- Settings -> Interface -> Window Background:  Opaque
Notice you can now read highlighted text 

Please see this demonstrated in this gif
![2020-09-25_02h45_44](https://user-images.githubusercontent.com/4992990/94235640-e6195680-fed9-11ea-9ce7-6bdd428a1db4.gif)

**Comment by sedwards2009** [comment] 2020-09-28 17:55
Which git tool and operating system you using in that gif?

**Comment by fhumayun** [comment] 2020-10-06 16:18
That's WSL2 ubuntu 20.04/Windows 10 
And I'm using ZIM/ZSH - anyway the issues isn't just with Git - but even selecting text within VIM or even just mouse selection of text.

**Comment by sedwards2009** [comment] 2020-10-12 10:50
I was just able to reproduce this problem on Windows + WSL2 with and without the background blur. In vim, selected text has a background colour which matches the the normal text colour exactly. Other terminals don't do this. This also happens on plain Linux.

**Comment by sedwards2009** [comment] 2020-10-13 17:54
The problem in vim appears to be vim using colours for selection which are very close to each other. Using a different terminal theme may help. You might be able configure vim's colours too.

The problem with that git tool in the gif you attached seems to be something different because it is changes so much when transparent background is on/off. Can you tell me which git tool that is and maybe also attach the 'Jellybean' theme you're using. Then I can try to reproduce the problem locally.

**Comment by fhumayun** [comment] 2021-01-02 06:07
Hi @sedwards2009 - Happy new year to you and the terrific exaterm development efforts.   Honestly - I had given up on that.  I ended up switching to ZINIT & ZSH using https://github.com/wfxr/forgit where exaterm behaves itself
![2021-01-02_01h05_04](https://user-images.githubusercontent.com/4992990/103451830-bfb44580-4c96-11eb-8ab0-d9dddb0d4c3d.gif)

However, I'm curious - if you try to paste to terminal from clipboard do you continue to experience the highlighted unreadability issue, like I do?
![2021-01-02_01h03_32](https://user-images.githubusercontent.com/4992990/103451834-dd81aa80-4c96-11eb-9ee8-3a3812995322.gif)

**Comment by sedwards2009** [comment] 2021-01-23 11:05
Fixed in v0.57.1

**Closed by sedwards2009** 2021-01-23 11:05 UTC
Labels: bug, prio:high
